### ISSUE TITLE
Not Working on OpenSUSE Tumbleweed

### ISSUE THREAD

**Issue by azisnaufal** [lakinduakash/linux-wifi-hotspot#93] opened 2020-11-04 02:53 UTC
I don't really know how to explain it. But when the wifi hotspot is started, it just show it is runnig at PID x.

Here is the log:

> oazisn@localhost:~/Applications/linux-wifi-hotspot$ wihotspot
> 
> (wihotspot-gui:10013): Gtk-WARNING **: 09:44:58.378: gtk_widget_size_allocate(): attempt to allocate widget with width 757 and height -4
> 
> (wihotspot-gui:10013): Gtk-WARNING **: 09:44:58.379: gtk_widget_size_allocate(): attempt to allocate widget with width 94 and height -1
> pkexec --user root create_ap wlp0s20f3 wlp0s20f3 'KantinSebelah' 'tumbl3w33d' --mkconfig /etc/wh.config --freq-band 2.4 -c 1 
> Config options written to '/etc/wh.config'
> Trying to kill create_ap instance associated with 10099...
> pkexec --user root create_ap wlp0s20f3 wlp0s20f3 'KantinSebelah' 'tumbl3w33d' --mkconfig /etc/wh.config -c 1 
> Config options written to '/etc/wh.config'
> 
> ERROR: Your adapter can not transmit to channel 1, frequency band 5GHz.
> 
> Command not found or exited with error status
> pkexec --user root create_ap wlp0s20f3 wlp0s20f3 'KantinSebelah' 'tumbl3w33d' --mkconfig /etc/wh.config 
> Config options written to '/etc/wh.config'
> 
> ERROR: Your adapter can not transmit to channel 1, frequency band 5GHz.
> 
> Command not found or exited with error status
> pkexec --user root create_ap wlp0s20f3 wlp0s20f3 'KantinSebelah' 'tumbl3w33d' --mkconfig /etc/wh.config --freq-band 5 
> Config options written to '/etc/wh.config'
> 
> ERROR: Your adapter can not transmit to channel 36, frequency band 5GHz.
> 
> Command not found or exited with error status
> pkexec --user root create_ap wlp0s20f3 wlp0s20f3 'KantinSebelah' 'tumbl3w33d' --mkconfig /etc/wh.config --freq-band 5 -c 161 
> Config options written to '/etc/wh.config'
> Trying to kill create_ap instance associated with 12460...

Here is the screenshot of wifi hostpot:
![image](https://user-images.githubusercontent.com/2264036/98063767-5f19af80-1e83-11eb-813a-3044dd05dd71.png)

Here is what ps ax tell about create_ap:
> oazisn@localhost:~/Applications/linux-wifi-hotspot$ ps ax | grep create_ap
> 10099 pts/1    Z+     0:00 [create_ap] <defunct>
> 12460 pts/1    Z+     0:00 [create_ap] <defunct>
> 15326 pts/1    Z+     0:00 [create_ap] <defunct>
> 15919 pts/2    S+     0:00 grep --color=auto create_ap
> oazisn@localhost:~/Applications/linux-wifi-hotspot$ 

What if i run create_ap manually?

> oazisn@localhost:~/Applications/linux-wifi-hotspot$ pkexec --user root create_ap wlp0s20f3 wlp0s20f3 'KantinSebelah' 'tumbl3w33d' --freq-band 5 -c 161                        Config dir: /tmp/create_ap.wlp0s20f3.conf.G0LoZt9z
> PID: 13138
> Network Manager found, set ap0 as unmanaged device... DONE
> Custom frequency band set with 5Mhz with channel 161
> Creating a virtual WiFi interface... ap0 created.
> Sharing Internet using method: nat
> Setting /usr/sbin/dnsmasq to complain mode.
> hostapd command-line interface: hostapd_cli -p /tmp/create_ap.wlp0s20f3.conf.G0LoZt9z/hostapd_ctrl
> Configuration file: /tmp/create_ap.wlp0s20f3.conf.G0LoZt9z/hostapd.conf
> Using interface ap0 with hwaddr f8:ac:65:26:ae:c7 and ssid "KantinSebelah"
> ap0: interface state UNINITIALIZED->ENABLED
> ap0: AP-ENABLED 
> ap0: STA d0:9c:7a:1d:3d:d8 IEEE 802.11: authenticated
> ap0: STA d0:9c:7a:1d:3d:d8 IEEE 802.11: associated (aid 1)
> ap0: AP-STA-CONNECTED d0:9c:7a:1d:3d:d8
> ap0: STA d0:9c:7a:1d:3d:d8 RADIUS: starting accounting session 2F84CC9F458481D9
> ap0: STA d0:9c:7a:1d:3d:d8 WPA: pairwise key handshake completed (RSN)

The wifi is accessibly at my phone.

**Comment by lakinduakash** [comment] 2020-11-04 04:16
Hi,
Did you check with 2.4Ghz band ? If not can you check that?

**Comment by azisnaufal** [comment] 2020-11-04 12:52
Here is 2.4 Ghz one.

Log: 
> oazisn@localhost:~$ wihotspot
> 
> (wihotspot-gui:10564): Gtk-WARNING **: 19:49:05.736: gtk_widget_size_allocate(): attempt to allocate widget with width 757 and height -4
> 
> (wihotspot-gui:10564): Gtk-WARNING **: 19:49:05.736: gtk_widget_size_allocate(): attempt to allocate widget with width 94 and height -1
> pkexec --user root create_ap wlp0s20f3 wlp0s20f3 'KantinSebelah' 'tumbl3w33d' --mkconfig /etc/wh.config --freq-band 2.4 -c 1 
> Config options written to '/etc/wh.config'

Screenshot :
![image](https://user-images.githubusercontent.com/2264036/98113969-08d65c00-1ed7-11eb-8221-4d48bf670537.png)

Here is what ps ax tell about create_ap:

> oazisn@localhost:~$ ps ax | grep create_ap
> 10631 pts/1    Z+     0:00 [create_ap] <defunct>
> 11120 pts/2    S+     0:00 grep --color=auto create_ap
> oazisn@localhost:~$ 

Creating manually:

> oazisn@localhost:~$ pkexec --user root create_ap wlp0s20f3 wlp0s20f3 'KantinSebelah' 'tumbl3w33d' --freq-band 2.4 -c 1
> Config dir: /tmp/create_ap.wlp0s20f3.conf.fc6I95gq
> PID: 11150
> Network Manager found, set ap0 as unmanaged device... DONE
> Custom frequency band set with 2.4Mhz with channel 1
> Creating a virtual WiFi interface... ap0 created.
> Sharing Internet using method: nat
> Setting /usr/sbin/dnsmasq to complain mode.
> hostapd command-line interface: hostapd_cli -p /tmp/create_ap.wlp0s20f3.conf.fc6I95gq/hostapd_ctrl
> Configuration file: /tmp/create_ap.wlp0s20f3.conf.fc6I95gq/hostapd.conf
> Using interface ap0 with hwaddr f8:ac:65:26:ae:c7 and ssid "KantinSebelah"
> ap0: interface state UNINITIALIZED->ENABLED
> ap0: AP-ENABLED 
> ap0: STA d0:9c:7a:1d:3d:d8 IEEE 802.11: authenticated
> ap0: STA d0:9c:7a:1d:3d:d8 IEEE 802.11: associated (aid 1)
> ap0: AP-STA-CONNECTED d0:9c:7a:1d:3d:d8
> ap0: STA d0:9c:7a:1d:3d:d8 RADIUS: starting accounting session AF92D1B0B015B1F3
> ap0: STA d0:9c:7a:1d:3d:d8 WPA: pairwise key handshake completed (RSN)
>

**Comment by lakinduakash** [comment] 2020-12-16 21:24
duplicate of #88

**Closed** 2023-05-15 18:23 UTC
