### ISSUE TITLE
can't create discoverable AP in GUI

### ISSUE THREAD

**Issue by ybrhue** [lakinduakash/linux-wifi-hotspot#103] opened 2020-11-22 17:59 UTC
**Describe the bug**
sudo create_ap --ieee80211ac --freq-band 2.4 wlp0s20f3 wlp0s20f3 YourSSID MyPassPhrase works in terminal but not in gui!

I select all the relevant fields (pw or no pw, SSID, 2,4 and ieee80211ac) but the AP is not discoverable.

**Desktop (please complete the following information):**
 - KDE latest from Manjaro Linux

**Additional context**
installed from aur

**Comment by lakinduakash** [comment] 2020-12-16 21:24
Duplicate of #88

**Closed** 2021-09-25 00:39 UTC
Labels: bug, duplicate, investigation-required
