### ISSUE TITLE
Low speed in 2.4 Ghz

### ISSUE THREAD

**Issue by VoXaN24** [lakinduakash/linux-wifi-hotspot#113] opened 2020-12-17 18:04 UTC
I have (it's relative) low speed in 2.4Ghz, like i have never upper that (Like 2.4Ghz can have 40~50 Mbps, i'm next to the PC)
![image](https://user-images.githubusercontent.com/30030208/102524213-f3894b80-4098-11eb-9d62-06f1104f7818.png)
Idk why that be (the channel can be the issue ? That can be weird because i have no other wifi in my area)

PS: I have a good fiber connexion, so that isn't the issue
![image](https://user-images.githubusercontent.com/30030208/102524368-2fbcac00-4099-11eb-98f4-20814c56a6af.png)

**Desktop (please complete the following information):**
![image](https://img.vhost.cf/4lxvj24p.png)

**Wifi card**
![image](https://img.vhost.cf/x1jqzzxc.png)

**Comment by VoXaN24** [comment] 2020-12-17 18:05
PS: I used in CLI list with create_ap command because i didn't have graphics interface

**Comment by VoXaN24** [comment] 2020-12-17 19:54
![Screenshot_20201217-205427446.jpg](https://user-images.githubusercontent.com/30030208/102536562-11ab7780-40aa-11eb-8855-5c17f23df4b9.jpg)
Tested with an other speedtest app : Same result

**Comment by reckel-jm** [comment] 2020-12-19 00:34
Hey,

I can confirm this issue. The reason seams to be that their is no noscan=1 option as does exists in /etc/hostapd/hostapd.conf. It should be good to add this option as a command line parameter for create_ap.

**Comment by lakinduakash** [comment] 2020-12-19 11:33
@reckel-jm So making no_scan=0 make it faster ?

**Comment by VoXaN24** [comment] 2020-12-20 12:01
noscan=1 added in hostapd.conf (In the command line that didn't work)
And same result but it's more stable ![Screenshot_20201220-125954253.jpg](https://user-images.githubusercontent.com/30030208/102712720-6e35af00-42c3-11eb-97b4-c8d626750fff.jpg)

**Comment by lakinduakash** [comment] 2020-12-22 14:03
Hi,
I think that speed is a limitation in the wifi adapter itself. Those equipped with laptops and phones are less powerful than routers. If you can do a test with mobile hotspot and built-in hotspot option in OS.

**Comment by ledlamp** [comment] 2020-12-24 08:36
It uses 802.11g... I think you have to check "IEEE80211n" or "IEEE80211ac" under Advanced to make it use the better n or ac modes for better speed.

**Comment by VoXaN24** [comment] 2020-12-24 08:43
> It uses 802.11g... I think you have to check "IEEE80211n" or "IEEE80211ac" under Advanced to make it use the better n or ac modes for better speed.

How can I made that ?

**Comment by lakinduakash** [comment] 2020-12-24 13:05
There is a option in UI or read the command line guide for enabling it

**Comment by ledlamp** [comment] 2020-12-24 20:09
Yesterday I wasn't getting great speeds and found that it was using 802.11g
https://cdn.discordapp.com/attachments/672956424162115586/791571998672814090/Screenshot_20201223-234410.png
A little better on my laptop... https://bsaa.qonq.gq

I checked these options
![](https://dgdu.qonq.gq)

Now it's using 802.11n and much better speed 
![](https://2ag2.qonq.gq)
(my internet service is 25/3 so this is fair. although it actually seems to be 30/3)
I got similar speed on my phone... 22.0 average

But Hmm... now I cannot create a 5ghz hotspot...

**Comment by ledlamp** [comment] 2020-12-24 20:15
Oops ![](https://rk1y.qonq.gq)

It worked yesterday 🤔

**Comment by ledlamp** [comment] 2020-12-24 20:57
Good speed with 802.11ac. ![](https://46zx.qonq.gq)

Faster than the internet service so I tested with http on LAN. 
![138mbps](https://rctj.qonq.gq)
Very nice.

**Comment by ledlamp** [comment] 2020-12-24 20:57
I think IEEE80211n and IEEE80211ac options should be enabled by default. Also 802.11ax support would be nice too.

**Comment by ledlamp** [comment] 2020-12-24 21:14
LAN test with 802.11n 2.4ghz:
![42.6 Mbps](https://vf7p.qonq.gq)

**Comment by lakinduakash** [comment] 2020-12-24 22:16
> I think IEEE80211n and IEEE80211ac options should be enabled by default. Also 802.11ax support would be nice too.

Great. I will look about it and make that by default. 

> Oops ![](https://camo.githubusercontent.com/aa22ffe3d3243f59486c136d231c866ae60f130cec5b3a2b1161f494bbe053a0/68747470733a2f2f726b31792e716f6e712e6771)
> 
> It worked yesterday 🤔 and on channel 36 too. Huh.
> 
> The only difference between now and then is I stopped NetworkManager.

That 5ghz issue is coming for long time. Sometimes it cause by that the driver is not supported. I have to analyse that bit more with network manager as well. But if it is supported with NetworkManager I think that's sufficient. Might be it needs to add the NetworkManager as a dependency. 

And thank you for the tests and confirmation. I will close the issue. 🙂

**Closed by lakinduakash** 2020-12-24 22:16 UTC
Labels: discussion

**Comment by lakinduakash** [comment] 2024-01-09 22:34
802.11ax support is added
